target_connection_string: "Driver={SQL Server Native Client 11.0};Server=.;Database=SingaporeEmigration;Trusted_Connection=yes;"
source_file_location: "data/economy_new.csv"
table_name: dimeconomy
key_in_fact_master: economyid